name: Build and Tag

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        run: |
          staging lint
      - name: Test
        run: |
          staging test
  tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
      
    steps:
      - uses: actions/checkout@v4
      - name: Check bump
        id: vbump
        uses: rgryta/Check-Bump@v1.0.2
        with:
          prefix: 'v'
      - name: Push Tag
        uses: actions/github-script@v7
        if: steps.vbump.outputs.bump == 'true'
        with:
          github-token: ${{ secrets.GH_ACTIONS_TOKEN }}  # PAT Token that has repo and hooks permissions (403 or 404 HTTP errors otherwise)
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.vbump.outputs.version }}",
              sha: context.sha
            })
