name: Release a New Version

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}  # PAT Token that has repo and hooks permissions (403 or 404 HTTP errors otherwise)
